include: [".well-known"]

defaults:
  - scope:
      path: ".well-known/apple-app-site-association"
    values:
      layout: null
      content_type: "application/json"
- scope:
      path: ".well-known/assetlinks.json"
    values:
      layout: null
      content_type: "application/json"
